title = "Appjack Studio"
baseURL = "https://appjackstudio.com/"
languageCode = "en-us"
theme = "ananke"

sectionPagesMenu = "main"

[params]
  favicon = "favicon.ico"
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/bmxguy100"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"

[blackFriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true